# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
    - libmagick++-dev
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
  - Rscript -e 'install.packages("XML", repos = "http://www.omegahat.net/R")'
